// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-protos-go-apiv2/common"
	"github.com/hyperledger/fabric-x-orderer/node/consensus/synchronizer"
)

type FakeHeightDetector struct {
	CloseStub        func()
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
	}
	GenesisByEndpointsStub        func() (map[string]*common.Block, error)
	genesisByEndpointsMutex       sync.RWMutex
	genesisByEndpointsArgsForCall []struct {
	}
	genesisByEndpointsReturns struct {
		result1 map[string]*common.Block
		result2 error
	}
	genesisByEndpointsReturnsOnCall map[int]struct {
		result1 map[string]*common.Block
		result2 error
	}
	HeightsByEndpointsStub        func() (map[string]uint64, string, error)
	heightsByEndpointsMutex       sync.RWMutex
	heightsByEndpointsArgsForCall []struct {
	}
	heightsByEndpointsReturns struct {
		result1 map[string]uint64
		result2 string
		result3 error
	}
	heightsByEndpointsReturnsOnCall map[int]struct {
		result1 map[string]uint64
		result2 string
		result3 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeHeightDetector) Close() {
	fake.closeMutex.Lock()
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
	}{})
	stub := fake.CloseStub
	fake.recordInvocation("Close", []interface{}{})
	fake.closeMutex.Unlock()
	if stub != nil {
		fake.CloseStub()
	}
}

func (fake *FakeHeightDetector) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeHeightDetector) CloseCalls(stub func()) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeHeightDetector) GenesisByEndpoints() (map[string]*common.Block, error) {
	fake.genesisByEndpointsMutex.Lock()
	ret, specificReturn := fake.genesisByEndpointsReturnsOnCall[len(fake.genesisByEndpointsArgsForCall)]
	fake.genesisByEndpointsArgsForCall = append(fake.genesisByEndpointsArgsForCall, struct {
	}{})
	stub := fake.GenesisByEndpointsStub
	fakeReturns := fake.genesisByEndpointsReturns
	fake.recordInvocation("GenesisByEndpoints", []interface{}{})
	fake.genesisByEndpointsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeHeightDetector) GenesisByEndpointsCallCount() int {
	fake.genesisByEndpointsMutex.RLock()
	defer fake.genesisByEndpointsMutex.RUnlock()
	return len(fake.genesisByEndpointsArgsForCall)
}

func (fake *FakeHeightDetector) GenesisByEndpointsCalls(stub func() (map[string]*common.Block, error)) {
	fake.genesisByEndpointsMutex.Lock()
	defer fake.genesisByEndpointsMutex.Unlock()
	fake.GenesisByEndpointsStub = stub
}

func (fake *FakeHeightDetector) GenesisByEndpointsReturns(result1 map[string]*common.Block, result2 error) {
	fake.genesisByEndpointsMutex.Lock()
	defer fake.genesisByEndpointsMutex.Unlock()
	fake.GenesisByEndpointsStub = nil
	fake.genesisByEndpointsReturns = struct {
		result1 map[string]*common.Block
		result2 error
	}{result1, result2}
}

func (fake *FakeHeightDetector) GenesisByEndpointsReturnsOnCall(i int, result1 map[string]*common.Block, result2 error) {
	fake.genesisByEndpointsMutex.Lock()
	defer fake.genesisByEndpointsMutex.Unlock()
	fake.GenesisByEndpointsStub = nil
	if fake.genesisByEndpointsReturnsOnCall == nil {
		fake.genesisByEndpointsReturnsOnCall = make(map[int]struct {
			result1 map[string]*common.Block
			result2 error
		})
	}
	fake.genesisByEndpointsReturnsOnCall[i] = struct {
		result1 map[string]*common.Block
		result2 error
	}{result1, result2}
}

func (fake *FakeHeightDetector) HeightsByEndpoints() (map[string]uint64, string, error) {
	fake.heightsByEndpointsMutex.Lock()
	ret, specificReturn := fake.heightsByEndpointsReturnsOnCall[len(fake.heightsByEndpointsArgsForCall)]
	fake.heightsByEndpointsArgsForCall = append(fake.heightsByEndpointsArgsForCall, struct {
	}{})
	stub := fake.HeightsByEndpointsStub
	fakeReturns := fake.heightsByEndpointsReturns
	fake.recordInvocation("HeightsByEndpoints", []interface{}{})
	fake.heightsByEndpointsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1, ret.result2, ret.result3
	}
	return fakeReturns.result1, fakeReturns.result2, fakeReturns.result3
}

func (fake *FakeHeightDetector) HeightsByEndpointsCallCount() int {
	fake.heightsByEndpointsMutex.RLock()
	defer fake.heightsByEndpointsMutex.RUnlock()
	return len(fake.heightsByEndpointsArgsForCall)
}

func (fake *FakeHeightDetector) HeightsByEndpointsCalls(stub func() (map[string]uint64, string, error)) {
	fake.heightsByEndpointsMutex.Lock()
	defer fake.heightsByEndpointsMutex.Unlock()
	fake.HeightsByEndpointsStub = stub
}

func (fake *FakeHeightDetector) HeightsByEndpointsReturns(result1 map[string]uint64, result2 string, result3 error) {
	fake.heightsByEndpointsMutex.Lock()
	defer fake.heightsByEndpointsMutex.Unlock()
	fake.HeightsByEndpointsStub = nil
	fake.heightsByEndpointsReturns = struct {
		result1 map[string]uint64
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeHeightDetector) HeightsByEndpointsReturnsOnCall(i int, result1 map[string]uint64, result2 string, result3 error) {
	fake.heightsByEndpointsMutex.Lock()
	defer fake.heightsByEndpointsMutex.Unlock()
	fake.HeightsByEndpointsStub = nil
	if fake.heightsByEndpointsReturnsOnCall == nil {
		fake.heightsByEndpointsReturnsOnCall = make(map[int]struct {
			result1 map[string]uint64
			result2 string
			result3 error
		})
	}
	fake.heightsByEndpointsReturnsOnCall[i] = struct {
		result1 map[string]uint64
		result2 string
		result3 error
	}{result1, result2, result3}
}

func (fake *FakeHeightDetector) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	fake.genesisByEndpointsMutex.RLock()
	defer fake.genesisByEndpointsMutex.RUnlock()
	fake.heightsByEndpointsMutex.RLock()
	defer fake.heightsByEndpointsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeHeightDetector) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ synchronizer.HeightDetector = new(FakeHeightDetector)
