// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-lib-go/bccsp"
	"github.com/hyperledger/fabric-lib-go/common/flogging"
	"github.com/hyperledger/fabric-x-orderer/common/types"
	"github.com/hyperledger/fabric-x-orderer/config"
	"github.com/hyperledger/fabric-x-orderer/node/comm"
	"github.com/hyperledger/fabric-x-orderer/node/consensus/synchronizer"
)

type FakeHeightDetectorFactory struct {
	CreateHeightDetectorStub        func(types.PartyID, synchronizer.ConsenterSupport, *comm.PredicateDialer, config.Cluster, bccsp.BCCSP, *flogging.FabricLogger) (synchronizer.HeightDetector, error)
	createHeightDetectorMutex       sync.RWMutex
	createHeightDetectorArgsForCall []struct {
		arg1 types.PartyID
		arg2 synchronizer.ConsenterSupport
		arg3 *comm.PredicateDialer
		arg4 config.Cluster
		arg5 bccsp.BCCSP
		arg6 *flogging.FabricLogger
	}
	createHeightDetectorReturns struct {
		result1 synchronizer.HeightDetector
		result2 error
	}
	createHeightDetectorReturnsOnCall map[int]struct {
		result1 synchronizer.HeightDetector
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeHeightDetectorFactory) CreateHeightDetector(arg1 types.PartyID, arg2 synchronizer.ConsenterSupport, arg3 *comm.PredicateDialer, arg4 config.Cluster, arg5 bccsp.BCCSP, arg6 *flogging.FabricLogger) (synchronizer.HeightDetector, error) {
	fake.createHeightDetectorMutex.Lock()
	ret, specificReturn := fake.createHeightDetectorReturnsOnCall[len(fake.createHeightDetectorArgsForCall)]
	fake.createHeightDetectorArgsForCall = append(fake.createHeightDetectorArgsForCall, struct {
		arg1 types.PartyID
		arg2 synchronizer.ConsenterSupport
		arg3 *comm.PredicateDialer
		arg4 config.Cluster
		arg5 bccsp.BCCSP
		arg6 *flogging.FabricLogger
	}{arg1, arg2, arg3, arg4, arg5, arg6})
	stub := fake.CreateHeightDetectorStub
	fakeReturns := fake.createHeightDetectorReturns
	fake.recordInvocation("CreateHeightDetector", []interface{}{arg1, arg2, arg3, arg4, arg5, arg6})
	fake.createHeightDetectorMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeHeightDetectorFactory) CreateHeightDetectorCallCount() int {
	fake.createHeightDetectorMutex.RLock()
	defer fake.createHeightDetectorMutex.RUnlock()
	return len(fake.createHeightDetectorArgsForCall)
}

func (fake *FakeHeightDetectorFactory) CreateHeightDetectorCalls(stub func(types.PartyID, synchronizer.ConsenterSupport, *comm.PredicateDialer, config.Cluster, bccsp.BCCSP, *flogging.FabricLogger) (synchronizer.HeightDetector, error)) {
	fake.createHeightDetectorMutex.Lock()
	defer fake.createHeightDetectorMutex.Unlock()
	fake.CreateHeightDetectorStub = stub
}

func (fake *FakeHeightDetectorFactory) CreateHeightDetectorArgsForCall(i int) (types.PartyID, synchronizer.ConsenterSupport, *comm.PredicateDialer, config.Cluster, bccsp.BCCSP, *flogging.FabricLogger) {
	fake.createHeightDetectorMutex.RLock()
	defer fake.createHeightDetectorMutex.RUnlock()
	argsForCall := fake.createHeightDetectorArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6
}

func (fake *FakeHeightDetectorFactory) CreateHeightDetectorReturns(result1 synchronizer.HeightDetector, result2 error) {
	fake.createHeightDetectorMutex.Lock()
	defer fake.createHeightDetectorMutex.Unlock()
	fake.CreateHeightDetectorStub = nil
	fake.createHeightDetectorReturns = struct {
		result1 synchronizer.HeightDetector
		result2 error
	}{result1, result2}
}

func (fake *FakeHeightDetectorFactory) CreateHeightDetectorReturnsOnCall(i int, result1 synchronizer.HeightDetector, result2 error) {
	fake.createHeightDetectorMutex.Lock()
	defer fake.createHeightDetectorMutex.Unlock()
	fake.CreateHeightDetectorStub = nil
	if fake.createHeightDetectorReturnsOnCall == nil {
		fake.createHeightDetectorReturnsOnCall = make(map[int]struct {
			result1 synchronizer.HeightDetector
			result2 error
		})
	}
	fake.createHeightDetectorReturnsOnCall[i] = struct {
		result1 synchronizer.HeightDetector
		result2 error
	}{result1, result2}
}

func (fake *FakeHeightDetectorFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createHeightDetectorMutex.RLock()
	defer fake.createHeightDetectorMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeHeightDetectorFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ synchronizer.HeightDetectorFactory = new(FakeHeightDetectorFactory)
