// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-lib-go/common/flogging"
	"github.com/hyperledger/fabric-x-orderer/node/config"
	"github.com/hyperledger/fabric-x-orderer/node/delivery"
	"github.com/hyperledger/fabric-x-orderer/node/ledger"
)

type FakeConsensusBringerFactory struct {
	CreateStub        func(string, []config.RawBytes, config.RawBytes, config.RawBytes, string, ledger.AssemblerLedgerReaderWriter, *flogging.FabricLogger) delivery.ConsensusBringer
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 string
		arg2 []config.RawBytes
		arg3 config.RawBytes
		arg4 config.RawBytes
		arg5 string
		arg6 ledger.AssemblerLedgerReaderWriter
		arg7 *flogging.FabricLogger
	}
	createReturns struct {
		result1 delivery.ConsensusBringer
	}
	createReturnsOnCall map[int]struct {
		result1 delivery.ConsensusBringer
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeConsensusBringerFactory) Create(arg1 string, arg2 []config.RawBytes, arg3 config.RawBytes, arg4 config.RawBytes, arg5 string, arg6 ledger.AssemblerLedgerReaderWriter, arg7 *flogging.FabricLogger) delivery.ConsensusBringer {
	var arg2Copy []config.RawBytes
	if arg2 != nil {
		arg2Copy = make([]config.RawBytes, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 string
		arg2 []config.RawBytes
		arg3 config.RawBytes
		arg4 config.RawBytes
		arg5 string
		arg6 ledger.AssemblerLedgerReaderWriter
		arg7 *flogging.FabricLogger
	}{arg1, arg2Copy, arg3, arg4, arg5, arg6, arg7})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1, arg2Copy, arg3, arg4, arg5, arg6, arg7})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5, arg6, arg7)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeConsensusBringerFactory) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeConsensusBringerFactory) CreateCalls(stub func(string, []config.RawBytes, config.RawBytes, config.RawBytes, string, ledger.AssemblerLedgerReaderWriter, *flogging.FabricLogger) delivery.ConsensusBringer) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *FakeConsensusBringerFactory) CreateArgsForCall(i int) (string, []config.RawBytes, config.RawBytes, config.RawBytes, string, ledger.AssemblerLedgerReaderWriter, *flogging.FabricLogger) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5, argsForCall.arg6, argsForCall.arg7
}

func (fake *FakeConsensusBringerFactory) CreateReturns(result1 delivery.ConsensusBringer) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 delivery.ConsensusBringer
	}{result1}
}

func (fake *FakeConsensusBringerFactory) CreateReturnsOnCall(i int, result1 delivery.ConsensusBringer) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 delivery.ConsensusBringer
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 delivery.ConsensusBringer
	}{result1}
}

func (fake *FakeConsensusBringerFactory) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeConsensusBringerFactory) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ delivery.ConsensusBringerFactory = new(FakeConsensusBringerFactory)
