// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-protos-go-apiv2/common"
)

type FakeConfigtxValidator struct {
	ChannelIDStub        func() string
	channelIDMutex       sync.RWMutex
	channelIDArgsForCall []struct {
	}
	channelIDReturns struct {
		result1 string
	}
	channelIDReturnsOnCall map[int]struct {
		result1 string
	}
	ConfigProtoStub        func() *common.Config
	configProtoMutex       sync.RWMutex
	configProtoArgsForCall []struct {
	}
	configProtoReturns struct {
		result1 *common.Config
	}
	configProtoReturnsOnCall map[int]struct {
		result1 *common.Config
	}
	ProposeConfigUpdateStub        func(*common.Envelope) (*common.ConfigEnvelope, error)
	proposeConfigUpdateMutex       sync.RWMutex
	proposeConfigUpdateArgsForCall []struct {
		arg1 *common.Envelope
	}
	proposeConfigUpdateReturns struct {
		result1 *common.ConfigEnvelope
		result2 error
	}
	proposeConfigUpdateReturnsOnCall map[int]struct {
		result1 *common.ConfigEnvelope
		result2 error
	}
	SequenceStub        func() uint64
	sequenceMutex       sync.RWMutex
	sequenceArgsForCall []struct {
	}
	sequenceReturns struct {
		result1 uint64
	}
	sequenceReturnsOnCall map[int]struct {
		result1 uint64
	}
	ValidateStub        func(*common.ConfigEnvelope) error
	validateMutex       sync.RWMutex
	validateArgsForCall []struct {
		arg1 *common.ConfigEnvelope
	}
	validateReturns struct {
		result1 error
	}
	validateReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeConfigtxValidator) ChannelID() string {
	fake.channelIDMutex.Lock()
	ret, specificReturn := fake.channelIDReturnsOnCall[len(fake.channelIDArgsForCall)]
	fake.channelIDArgsForCall = append(fake.channelIDArgsForCall, struct {
	}{})
	stub := fake.ChannelIDStub
	fakeReturns := fake.channelIDReturns
	fake.recordInvocation("ChannelID", []interface{}{})
	fake.channelIDMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeConfigtxValidator) ChannelIDCallCount() int {
	fake.channelIDMutex.RLock()
	defer fake.channelIDMutex.RUnlock()
	return len(fake.channelIDArgsForCall)
}

func (fake *FakeConfigtxValidator) ChannelIDCalls(stub func() string) {
	fake.channelIDMutex.Lock()
	defer fake.channelIDMutex.Unlock()
	fake.ChannelIDStub = stub
}

func (fake *FakeConfigtxValidator) ChannelIDReturns(result1 string) {
	fake.channelIDMutex.Lock()
	defer fake.channelIDMutex.Unlock()
	fake.ChannelIDStub = nil
	fake.channelIDReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeConfigtxValidator) ChannelIDReturnsOnCall(i int, result1 string) {
	fake.channelIDMutex.Lock()
	defer fake.channelIDMutex.Unlock()
	fake.ChannelIDStub = nil
	if fake.channelIDReturnsOnCall == nil {
		fake.channelIDReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.channelIDReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeConfigtxValidator) ConfigProto() *common.Config {
	fake.configProtoMutex.Lock()
	ret, specificReturn := fake.configProtoReturnsOnCall[len(fake.configProtoArgsForCall)]
	fake.configProtoArgsForCall = append(fake.configProtoArgsForCall, struct {
	}{})
	stub := fake.ConfigProtoStub
	fakeReturns := fake.configProtoReturns
	fake.recordInvocation("ConfigProto", []interface{}{})
	fake.configProtoMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeConfigtxValidator) ConfigProtoCallCount() int {
	fake.configProtoMutex.RLock()
	defer fake.configProtoMutex.RUnlock()
	return len(fake.configProtoArgsForCall)
}

func (fake *FakeConfigtxValidator) ConfigProtoCalls(stub func() *common.Config) {
	fake.configProtoMutex.Lock()
	defer fake.configProtoMutex.Unlock()
	fake.ConfigProtoStub = stub
}

func (fake *FakeConfigtxValidator) ConfigProtoReturns(result1 *common.Config) {
	fake.configProtoMutex.Lock()
	defer fake.configProtoMutex.Unlock()
	fake.ConfigProtoStub = nil
	fake.configProtoReturns = struct {
		result1 *common.Config
	}{result1}
}

func (fake *FakeConfigtxValidator) ConfigProtoReturnsOnCall(i int, result1 *common.Config) {
	fake.configProtoMutex.Lock()
	defer fake.configProtoMutex.Unlock()
	fake.ConfigProtoStub = nil
	if fake.configProtoReturnsOnCall == nil {
		fake.configProtoReturnsOnCall = make(map[int]struct {
			result1 *common.Config
		})
	}
	fake.configProtoReturnsOnCall[i] = struct {
		result1 *common.Config
	}{result1}
}

func (fake *FakeConfigtxValidator) ProposeConfigUpdate(arg1 *common.Envelope) (*common.ConfigEnvelope, error) {
	fake.proposeConfigUpdateMutex.Lock()
	ret, specificReturn := fake.proposeConfigUpdateReturnsOnCall[len(fake.proposeConfigUpdateArgsForCall)]
	fake.proposeConfigUpdateArgsForCall = append(fake.proposeConfigUpdateArgsForCall, struct {
		arg1 *common.Envelope
	}{arg1})
	stub := fake.ProposeConfigUpdateStub
	fakeReturns := fake.proposeConfigUpdateReturns
	fake.recordInvocation("ProposeConfigUpdate", []interface{}{arg1})
	fake.proposeConfigUpdateMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeConfigtxValidator) ProposeConfigUpdateCallCount() int {
	fake.proposeConfigUpdateMutex.RLock()
	defer fake.proposeConfigUpdateMutex.RUnlock()
	return len(fake.proposeConfigUpdateArgsForCall)
}

func (fake *FakeConfigtxValidator) ProposeConfigUpdateCalls(stub func(*common.Envelope) (*common.ConfigEnvelope, error)) {
	fake.proposeConfigUpdateMutex.Lock()
	defer fake.proposeConfigUpdateMutex.Unlock()
	fake.ProposeConfigUpdateStub = stub
}

func (fake *FakeConfigtxValidator) ProposeConfigUpdateArgsForCall(i int) *common.Envelope {
	fake.proposeConfigUpdateMutex.RLock()
	defer fake.proposeConfigUpdateMutex.RUnlock()
	argsForCall := fake.proposeConfigUpdateArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeConfigtxValidator) ProposeConfigUpdateReturns(result1 *common.ConfigEnvelope, result2 error) {
	fake.proposeConfigUpdateMutex.Lock()
	defer fake.proposeConfigUpdateMutex.Unlock()
	fake.ProposeConfigUpdateStub = nil
	fake.proposeConfigUpdateReturns = struct {
		result1 *common.ConfigEnvelope
		result2 error
	}{result1, result2}
}

func (fake *FakeConfigtxValidator) ProposeConfigUpdateReturnsOnCall(i int, result1 *common.ConfigEnvelope, result2 error) {
	fake.proposeConfigUpdateMutex.Lock()
	defer fake.proposeConfigUpdateMutex.Unlock()
	fake.ProposeConfigUpdateStub = nil
	if fake.proposeConfigUpdateReturnsOnCall == nil {
		fake.proposeConfigUpdateReturnsOnCall = make(map[int]struct {
			result1 *common.ConfigEnvelope
			result2 error
		})
	}
	fake.proposeConfigUpdateReturnsOnCall[i] = struct {
		result1 *common.ConfigEnvelope
		result2 error
	}{result1, result2}
}

func (fake *FakeConfigtxValidator) Sequence() uint64 {
	fake.sequenceMutex.Lock()
	ret, specificReturn := fake.sequenceReturnsOnCall[len(fake.sequenceArgsForCall)]
	fake.sequenceArgsForCall = append(fake.sequenceArgsForCall, struct {
	}{})
	stub := fake.SequenceStub
	fakeReturns := fake.sequenceReturns
	fake.recordInvocation("Sequence", []interface{}{})
	fake.sequenceMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeConfigtxValidator) SequenceCallCount() int {
	fake.sequenceMutex.RLock()
	defer fake.sequenceMutex.RUnlock()
	return len(fake.sequenceArgsForCall)
}

func (fake *FakeConfigtxValidator) SequenceCalls(stub func() uint64) {
	fake.sequenceMutex.Lock()
	defer fake.sequenceMutex.Unlock()
	fake.SequenceStub = stub
}

func (fake *FakeConfigtxValidator) SequenceReturns(result1 uint64) {
	fake.sequenceMutex.Lock()
	defer fake.sequenceMutex.Unlock()
	fake.SequenceStub = nil
	fake.sequenceReturns = struct {
		result1 uint64
	}{result1}
}

func (fake *FakeConfigtxValidator) SequenceReturnsOnCall(i int, result1 uint64) {
	fake.sequenceMutex.Lock()
	defer fake.sequenceMutex.Unlock()
	fake.SequenceStub = nil
	if fake.sequenceReturnsOnCall == nil {
		fake.sequenceReturnsOnCall = make(map[int]struct {
			result1 uint64
		})
	}
	fake.sequenceReturnsOnCall[i] = struct {
		result1 uint64
	}{result1}
}

func (fake *FakeConfigtxValidator) Validate(arg1 *common.ConfigEnvelope) error {
	fake.validateMutex.Lock()
	ret, specificReturn := fake.validateReturnsOnCall[len(fake.validateArgsForCall)]
	fake.validateArgsForCall = append(fake.validateArgsForCall, struct {
		arg1 *common.ConfigEnvelope
	}{arg1})
	stub := fake.ValidateStub
	fakeReturns := fake.validateReturns
	fake.recordInvocation("Validate", []interface{}{arg1})
	fake.validateMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeConfigtxValidator) ValidateCallCount() int {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	return len(fake.validateArgsForCall)
}

func (fake *FakeConfigtxValidator) ValidateCalls(stub func(*common.ConfigEnvelope) error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = stub
}

func (fake *FakeConfigtxValidator) ValidateArgsForCall(i int) *common.ConfigEnvelope {
	fake.validateMutex.RLock()
	defer fake.validateMutex.RUnlock()
	argsForCall := fake.validateArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeConfigtxValidator) ValidateReturns(result1 error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = nil
	fake.validateReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeConfigtxValidator) ValidateReturnsOnCall(i int, result1 error) {
	fake.validateMutex.Lock()
	defer fake.validateMutex.Unlock()
	fake.ValidateStub = nil
	if fake.validateReturnsOnCall == nil {
		fake.validateReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeConfigtxValidator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeConfigtxValidator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
