// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-lib-go/bccsp"
	"github.com/hyperledger/fabric-protos-go-apiv2/common"
	"github.com/hyperledger/fabric-x-common/common/channelconfig"
	"github.com/hyperledger/fabric-x-common/protoutil/identity"
	"github.com/hyperledger/fabric-x-orderer/common/policy"
	"github.com/hyperledger/fabric-x-orderer/common/requestfilter"
	"github.com/hyperledger/fabric-x-orderer/node/protos/comm"
)

type FakeConfigUpdateProposer struct {
	AuthorizeAndVerifyConfigUpdateStub        func(*common.Envelope, channelconfig.Resources, bccsp.BCCSP) (*common.ConfigEnvelope, error)
	authorizeAndVerifyConfigUpdateMutex       sync.RWMutex
	authorizeAndVerifyConfigUpdateArgsForCall []struct {
		arg1 *common.Envelope
		arg2 channelconfig.Resources
		arg3 bccsp.BCCSP
	}
	authorizeAndVerifyConfigUpdateReturns struct {
		result1 *common.ConfigEnvelope
		result2 error
	}
	authorizeAndVerifyConfigUpdateReturnsOnCall map[int]struct {
		result1 *common.ConfigEnvelope
		result2 error
	}
	ProposeConfigUpdateStub        func(*comm.Request, channelconfig.Resources, identity.SignerSerializer, *requestfilter.RulesVerifier, bccsp.BCCSP) (*comm.Request, error)
	proposeConfigUpdateMutex       sync.RWMutex
	proposeConfigUpdateArgsForCall []struct {
		arg1 *comm.Request
		arg2 channelconfig.Resources
		arg3 identity.SignerSerializer
		arg4 *requestfilter.RulesVerifier
		arg5 bccsp.BCCSP
	}
	proposeConfigUpdateReturns struct {
		result1 *comm.Request
		result2 error
	}
	proposeConfigUpdateReturnsOnCall map[int]struct {
		result1 *comm.Request
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeConfigUpdateProposer) AuthorizeAndVerifyConfigUpdate(arg1 *common.Envelope, arg2 channelconfig.Resources, arg3 bccsp.BCCSP) (*common.ConfigEnvelope, error) {
	fake.authorizeAndVerifyConfigUpdateMutex.Lock()
	ret, specificReturn := fake.authorizeAndVerifyConfigUpdateReturnsOnCall[len(fake.authorizeAndVerifyConfigUpdateArgsForCall)]
	fake.authorizeAndVerifyConfigUpdateArgsForCall = append(fake.authorizeAndVerifyConfigUpdateArgsForCall, struct {
		arg1 *common.Envelope
		arg2 channelconfig.Resources
		arg3 bccsp.BCCSP
	}{arg1, arg2, arg3})
	stub := fake.AuthorizeAndVerifyConfigUpdateStub
	fakeReturns := fake.authorizeAndVerifyConfigUpdateReturns
	fake.recordInvocation("AuthorizeAndVerifyConfigUpdate", []interface{}{arg1, arg2, arg3})
	fake.authorizeAndVerifyConfigUpdateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeConfigUpdateProposer) AuthorizeAndVerifyConfigUpdateCallCount() int {
	fake.authorizeAndVerifyConfigUpdateMutex.RLock()
	defer fake.authorizeAndVerifyConfigUpdateMutex.RUnlock()
	return len(fake.authorizeAndVerifyConfigUpdateArgsForCall)
}

func (fake *FakeConfigUpdateProposer) AuthorizeAndVerifyConfigUpdateCalls(stub func(*common.Envelope, channelconfig.Resources, bccsp.BCCSP) (*common.ConfigEnvelope, error)) {
	fake.authorizeAndVerifyConfigUpdateMutex.Lock()
	defer fake.authorizeAndVerifyConfigUpdateMutex.Unlock()
	fake.AuthorizeAndVerifyConfigUpdateStub = stub
}

func (fake *FakeConfigUpdateProposer) AuthorizeAndVerifyConfigUpdateArgsForCall(i int) (*common.Envelope, channelconfig.Resources, bccsp.BCCSP) {
	fake.authorizeAndVerifyConfigUpdateMutex.RLock()
	defer fake.authorizeAndVerifyConfigUpdateMutex.RUnlock()
	argsForCall := fake.authorizeAndVerifyConfigUpdateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeConfigUpdateProposer) AuthorizeAndVerifyConfigUpdateReturns(result1 *common.ConfigEnvelope, result2 error) {
	fake.authorizeAndVerifyConfigUpdateMutex.Lock()
	defer fake.authorizeAndVerifyConfigUpdateMutex.Unlock()
	fake.AuthorizeAndVerifyConfigUpdateStub = nil
	fake.authorizeAndVerifyConfigUpdateReturns = struct {
		result1 *common.ConfigEnvelope
		result2 error
	}{result1, result2}
}

func (fake *FakeConfigUpdateProposer) AuthorizeAndVerifyConfigUpdateReturnsOnCall(i int, result1 *common.ConfigEnvelope, result2 error) {
	fake.authorizeAndVerifyConfigUpdateMutex.Lock()
	defer fake.authorizeAndVerifyConfigUpdateMutex.Unlock()
	fake.AuthorizeAndVerifyConfigUpdateStub = nil
	if fake.authorizeAndVerifyConfigUpdateReturnsOnCall == nil {
		fake.authorizeAndVerifyConfigUpdateReturnsOnCall = make(map[int]struct {
			result1 *common.ConfigEnvelope
			result2 error
		})
	}
	fake.authorizeAndVerifyConfigUpdateReturnsOnCall[i] = struct {
		result1 *common.ConfigEnvelope
		result2 error
	}{result1, result2}
}

func (fake *FakeConfigUpdateProposer) ProposeConfigUpdate(arg1 *comm.Request, arg2 channelconfig.Resources, arg3 identity.SignerSerializer, arg4 *requestfilter.RulesVerifier, arg5 bccsp.BCCSP) (*comm.Request, error) {
	fake.proposeConfigUpdateMutex.Lock()
	ret, specificReturn := fake.proposeConfigUpdateReturnsOnCall[len(fake.proposeConfigUpdateArgsForCall)]
	fake.proposeConfigUpdateArgsForCall = append(fake.proposeConfigUpdateArgsForCall, struct {
		arg1 *comm.Request
		arg2 channelconfig.Resources
		arg3 identity.SignerSerializer
		arg4 *requestfilter.RulesVerifier
		arg5 bccsp.BCCSP
	}{arg1, arg2, arg3, arg4, arg5})
	stub := fake.ProposeConfigUpdateStub
	fakeReturns := fake.proposeConfigUpdateReturns
	fake.recordInvocation("ProposeConfigUpdate", []interface{}{arg1, arg2, arg3, arg4, arg5})
	fake.proposeConfigUpdateMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeConfigUpdateProposer) ProposeConfigUpdateCallCount() int {
	fake.proposeConfigUpdateMutex.RLock()
	defer fake.proposeConfigUpdateMutex.RUnlock()
	return len(fake.proposeConfigUpdateArgsForCall)
}

func (fake *FakeConfigUpdateProposer) ProposeConfigUpdateCalls(stub func(*comm.Request, channelconfig.Resources, identity.SignerSerializer, *requestfilter.RulesVerifier, bccsp.BCCSP) (*comm.Request, error)) {
	fake.proposeConfigUpdateMutex.Lock()
	defer fake.proposeConfigUpdateMutex.Unlock()
	fake.ProposeConfigUpdateStub = stub
}

func (fake *FakeConfigUpdateProposer) ProposeConfigUpdateArgsForCall(i int) (*comm.Request, channelconfig.Resources, identity.SignerSerializer, *requestfilter.RulesVerifier, bccsp.BCCSP) {
	fake.proposeConfigUpdateMutex.RLock()
	defer fake.proposeConfigUpdateMutex.RUnlock()
	argsForCall := fake.proposeConfigUpdateArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeConfigUpdateProposer) ProposeConfigUpdateReturns(result1 *comm.Request, result2 error) {
	fake.proposeConfigUpdateMutex.Lock()
	defer fake.proposeConfigUpdateMutex.Unlock()
	fake.ProposeConfigUpdateStub = nil
	fake.proposeConfigUpdateReturns = struct {
		result1 *comm.Request
		result2 error
	}{result1, result2}
}

func (fake *FakeConfigUpdateProposer) ProposeConfigUpdateReturnsOnCall(i int, result1 *comm.Request, result2 error) {
	fake.proposeConfigUpdateMutex.Lock()
	defer fake.proposeConfigUpdateMutex.Unlock()
	fake.ProposeConfigUpdateStub = nil
	if fake.proposeConfigUpdateReturnsOnCall == nil {
		fake.proposeConfigUpdateReturnsOnCall = make(map[int]struct {
			result1 *comm.Request
			result2 error
		})
	}
	fake.proposeConfigUpdateReturnsOnCall[i] = struct {
		result1 *comm.Request
		result2 error
	}{result1, result2}
}

func (fake *FakeConfigUpdateProposer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeConfigUpdateProposer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ policy.ConfigUpdateProposer = new(FakeConfigUpdateProposer)
