// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-x-orderer/common/types"
	"github.com/hyperledger/fabric-x-orderer/node/batcher"
)

type FakeBatchesPuller struct {
	PullBatchesStub        func(types.PartyID) <-chan types.Batch
	pullBatchesMutex       sync.RWMutex
	pullBatchesArgsForCall []struct {
		arg1 types.PartyID
	}
	pullBatchesReturns struct {
		result1 <-chan types.Batch
	}
	pullBatchesReturnsOnCall map[int]struct {
		result1 <-chan types.Batch
	}
	StopStub        func()
	stopMutex       sync.RWMutex
	stopArgsForCall []struct {
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBatchesPuller) PullBatches(arg1 types.PartyID) <-chan types.Batch {
	fake.pullBatchesMutex.Lock()
	ret, specificReturn := fake.pullBatchesReturnsOnCall[len(fake.pullBatchesArgsForCall)]
	fake.pullBatchesArgsForCall = append(fake.pullBatchesArgsForCall, struct {
		arg1 types.PartyID
	}{arg1})
	stub := fake.PullBatchesStub
	fakeReturns := fake.pullBatchesReturns
	fake.recordInvocation("PullBatches", []interface{}{arg1})
	fake.pullBatchesMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBatchesPuller) PullBatchesCallCount() int {
	fake.pullBatchesMutex.RLock()
	defer fake.pullBatchesMutex.RUnlock()
	return len(fake.pullBatchesArgsForCall)
}

func (fake *FakeBatchesPuller) PullBatchesCalls(stub func(types.PartyID) <-chan types.Batch) {
	fake.pullBatchesMutex.Lock()
	defer fake.pullBatchesMutex.Unlock()
	fake.PullBatchesStub = stub
}

func (fake *FakeBatchesPuller) PullBatchesArgsForCall(i int) types.PartyID {
	fake.pullBatchesMutex.RLock()
	defer fake.pullBatchesMutex.RUnlock()
	argsForCall := fake.pullBatchesArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeBatchesPuller) PullBatchesReturns(result1 <-chan types.Batch) {
	fake.pullBatchesMutex.Lock()
	defer fake.pullBatchesMutex.Unlock()
	fake.PullBatchesStub = nil
	fake.pullBatchesReturns = struct {
		result1 <-chan types.Batch
	}{result1}
}

func (fake *FakeBatchesPuller) PullBatchesReturnsOnCall(i int, result1 <-chan types.Batch) {
	fake.pullBatchesMutex.Lock()
	defer fake.pullBatchesMutex.Unlock()
	fake.PullBatchesStub = nil
	if fake.pullBatchesReturnsOnCall == nil {
		fake.pullBatchesReturnsOnCall = make(map[int]struct {
			result1 <-chan types.Batch
		})
	}
	fake.pullBatchesReturnsOnCall[i] = struct {
		result1 <-chan types.Batch
	}{result1}
}

func (fake *FakeBatchesPuller) Stop() {
	fake.stopMutex.Lock()
	fake.stopArgsForCall = append(fake.stopArgsForCall, struct {
	}{})
	stub := fake.StopStub
	fake.recordInvocation("Stop", []interface{}{})
	fake.stopMutex.Unlock()
	if stub != nil {
		fake.StopStub()
	}
}

func (fake *FakeBatchesPuller) StopCallCount() int {
	fake.stopMutex.RLock()
	defer fake.stopMutex.RUnlock()
	return len(fake.stopArgsForCall)
}

func (fake *FakeBatchesPuller) StopCalls(stub func()) {
	fake.stopMutex.Lock()
	defer fake.stopMutex.Unlock()
	fake.StopStub = stub
}

func (fake *FakeBatchesPuller) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.pullBatchesMutex.RLock()
	defer fake.pullBatchesMutex.RUnlock()
	fake.stopMutex.RLock()
	defer fake.stopMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBatchesPuller) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ batcher.BatchesPuller = new(FakeBatchesPuller)
