// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-x-orderer/common/types"
	"github.com/hyperledger/fabric-x-orderer/node/batcher"
)

type FakeConfigSequenceGetter struct {
	ConfigSequenceStub        func() types.ConfigSequence
	configSequenceMutex       sync.RWMutex
	configSequenceArgsForCall []struct {
	}
	configSequenceReturns struct {
		result1 types.ConfigSequence
	}
	configSequenceReturnsOnCall map[int]struct {
		result1 types.ConfigSequence
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeConfigSequenceGetter) ConfigSequence() types.ConfigSequence {
	fake.configSequenceMutex.Lock()
	ret, specificReturn := fake.configSequenceReturnsOnCall[len(fake.configSequenceArgsForCall)]
	fake.configSequenceArgsForCall = append(fake.configSequenceArgsForCall, struct {
	}{})
	stub := fake.ConfigSequenceStub
	fakeReturns := fake.configSequenceReturns
	fake.recordInvocation("ConfigSequence", []interface{}{})
	fake.configSequenceMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeConfigSequenceGetter) ConfigSequenceCallCount() int {
	fake.configSequenceMutex.RLock()
	defer fake.configSequenceMutex.RUnlock()
	return len(fake.configSequenceArgsForCall)
}

func (fake *FakeConfigSequenceGetter) ConfigSequenceCalls(stub func() types.ConfigSequence) {
	fake.configSequenceMutex.Lock()
	defer fake.configSequenceMutex.Unlock()
	fake.ConfigSequenceStub = stub
}

func (fake *FakeConfigSequenceGetter) ConfigSequenceReturns(result1 types.ConfigSequence) {
	fake.configSequenceMutex.Lock()
	defer fake.configSequenceMutex.Unlock()
	fake.ConfigSequenceStub = nil
	fake.configSequenceReturns = struct {
		result1 types.ConfigSequence
	}{result1}
}

func (fake *FakeConfigSequenceGetter) ConfigSequenceReturnsOnCall(i int, result1 types.ConfigSequence) {
	fake.configSequenceMutex.Lock()
	defer fake.configSequenceMutex.Unlock()
	fake.ConfigSequenceStub = nil
	if fake.configSequenceReturnsOnCall == nil {
		fake.configSequenceReturnsOnCall = make(map[int]struct {
			result1 types.ConfigSequence
		})
	}
	fake.configSequenceReturnsOnCall[i] = struct {
		result1 types.ConfigSequence
	}{result1}
}

func (fake *FakeConfigSequenceGetter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.configSequenceMutex.RLock()
	defer fake.configSequenceMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeConfigSequenceGetter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ batcher.ConfigSequenceGetter = new(FakeConfigSequenceGetter)
