// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-lib-go/common/flogging"
	"github.com/hyperledger/fabric-x-orderer/common/types"
	"github.com/hyperledger/fabric-x-orderer/node/batcher"
	"github.com/hyperledger/fabric-x-orderer/node/config"
)

type FakeConsensusDecisionReplicatorCreator struct {
	CreateDecisionConsensusReplicatorStub        func(*config.BatcherNodeConfig, *flogging.FabricLogger, types.DecisionNum) batcher.DecisionReplicator
	createDecisionConsensusReplicatorMutex       sync.RWMutex
	createDecisionConsensusReplicatorArgsForCall []struct {
		arg1 *config.BatcherNodeConfig
		arg2 *flogging.FabricLogger
		arg3 types.DecisionNum
	}
	createDecisionConsensusReplicatorReturns struct {
		result1 batcher.DecisionReplicator
	}
	createDecisionConsensusReplicatorReturnsOnCall map[int]struct {
		result1 batcher.DecisionReplicator
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeConsensusDecisionReplicatorCreator) CreateDecisionConsensusReplicator(arg1 *config.BatcherNodeConfig, arg2 *flogging.FabricLogger, arg3 types.DecisionNum) batcher.DecisionReplicator {
	fake.createDecisionConsensusReplicatorMutex.Lock()
	ret, specificReturn := fake.createDecisionConsensusReplicatorReturnsOnCall[len(fake.createDecisionConsensusReplicatorArgsForCall)]
	fake.createDecisionConsensusReplicatorArgsForCall = append(fake.createDecisionConsensusReplicatorArgsForCall, struct {
		arg1 *config.BatcherNodeConfig
		arg2 *flogging.FabricLogger
		arg3 types.DecisionNum
	}{arg1, arg2, arg3})
	stub := fake.CreateDecisionConsensusReplicatorStub
	fakeReturns := fake.createDecisionConsensusReplicatorReturns
	fake.recordInvocation("CreateDecisionConsensusReplicator", []interface{}{arg1, arg2, arg3})
	fake.createDecisionConsensusReplicatorMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeConsensusDecisionReplicatorCreator) CreateDecisionConsensusReplicatorCallCount() int {
	fake.createDecisionConsensusReplicatorMutex.RLock()
	defer fake.createDecisionConsensusReplicatorMutex.RUnlock()
	return len(fake.createDecisionConsensusReplicatorArgsForCall)
}

func (fake *FakeConsensusDecisionReplicatorCreator) CreateDecisionConsensusReplicatorCalls(stub func(*config.BatcherNodeConfig, *flogging.FabricLogger, types.DecisionNum) batcher.DecisionReplicator) {
	fake.createDecisionConsensusReplicatorMutex.Lock()
	defer fake.createDecisionConsensusReplicatorMutex.Unlock()
	fake.CreateDecisionConsensusReplicatorStub = stub
}

func (fake *FakeConsensusDecisionReplicatorCreator) CreateDecisionConsensusReplicatorArgsForCall(i int) (*config.BatcherNodeConfig, *flogging.FabricLogger, types.DecisionNum) {
	fake.createDecisionConsensusReplicatorMutex.RLock()
	defer fake.createDecisionConsensusReplicatorMutex.RUnlock()
	argsForCall := fake.createDecisionConsensusReplicatorArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeConsensusDecisionReplicatorCreator) CreateDecisionConsensusReplicatorReturns(result1 batcher.DecisionReplicator) {
	fake.createDecisionConsensusReplicatorMutex.Lock()
	defer fake.createDecisionConsensusReplicatorMutex.Unlock()
	fake.CreateDecisionConsensusReplicatorStub = nil
	fake.createDecisionConsensusReplicatorReturns = struct {
		result1 batcher.DecisionReplicator
	}{result1}
}

func (fake *FakeConsensusDecisionReplicatorCreator) CreateDecisionConsensusReplicatorReturnsOnCall(i int, result1 batcher.DecisionReplicator) {
	fake.createDecisionConsensusReplicatorMutex.Lock()
	defer fake.createDecisionConsensusReplicatorMutex.Unlock()
	fake.CreateDecisionConsensusReplicatorStub = nil
	if fake.createDecisionConsensusReplicatorReturnsOnCall == nil {
		fake.createDecisionConsensusReplicatorReturnsOnCall = make(map[int]struct {
			result1 batcher.DecisionReplicator
		})
	}
	fake.createDecisionConsensusReplicatorReturnsOnCall[i] = struct {
		result1 batcher.DecisionReplicator
	}{result1}
}

func (fake *FakeConsensusDecisionReplicatorCreator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createDecisionConsensusReplicatorMutex.RLock()
	defer fake.createDecisionConsensusReplicatorMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeConsensusDecisionReplicatorCreator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ batcher.ConsensusDecisionReplicatorCreator = new(FakeConsensusDecisionReplicatorCreator)
