// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-x-orderer/node/batcher"
	"github.com/hyperledger/fabric-x-orderer/node/consensus/state"
)

type FakeDecisionReplicator struct {
	ReplicateDecisionStub        func() <-chan *state.Header
	replicateDecisionMutex       sync.RWMutex
	replicateDecisionArgsForCall []struct {
	}
	replicateDecisionReturns struct {
		result1 <-chan *state.Header
	}
	replicateDecisionReturnsOnCall map[int]struct {
		result1 <-chan *state.Header
	}
	StopStub        func()
	stopMutex       sync.RWMutex
	stopArgsForCall []struct {
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDecisionReplicator) ReplicateDecision() <-chan *state.Header {
	fake.replicateDecisionMutex.Lock()
	ret, specificReturn := fake.replicateDecisionReturnsOnCall[len(fake.replicateDecisionArgsForCall)]
	fake.replicateDecisionArgsForCall = append(fake.replicateDecisionArgsForCall, struct {
	}{})
	stub := fake.ReplicateDecisionStub
	fakeReturns := fake.replicateDecisionReturns
	fake.recordInvocation("ReplicateDecision", []interface{}{})
	fake.replicateDecisionMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeDecisionReplicator) ReplicateDecisionCallCount() int {
	fake.replicateDecisionMutex.RLock()
	defer fake.replicateDecisionMutex.RUnlock()
	return len(fake.replicateDecisionArgsForCall)
}

func (fake *FakeDecisionReplicator) ReplicateDecisionCalls(stub func() <-chan *state.Header) {
	fake.replicateDecisionMutex.Lock()
	defer fake.replicateDecisionMutex.Unlock()
	fake.ReplicateDecisionStub = stub
}

func (fake *FakeDecisionReplicator) ReplicateDecisionReturns(result1 <-chan *state.Header) {
	fake.replicateDecisionMutex.Lock()
	defer fake.replicateDecisionMutex.Unlock()
	fake.ReplicateDecisionStub = nil
	fake.replicateDecisionReturns = struct {
		result1 <-chan *state.Header
	}{result1}
}

func (fake *FakeDecisionReplicator) ReplicateDecisionReturnsOnCall(i int, result1 <-chan *state.Header) {
	fake.replicateDecisionMutex.Lock()
	defer fake.replicateDecisionMutex.Unlock()
	fake.ReplicateDecisionStub = nil
	if fake.replicateDecisionReturnsOnCall == nil {
		fake.replicateDecisionReturnsOnCall = make(map[int]struct {
			result1 <-chan *state.Header
		})
	}
	fake.replicateDecisionReturnsOnCall[i] = struct {
		result1 <-chan *state.Header
	}{result1}
}

func (fake *FakeDecisionReplicator) Stop() {
	fake.stopMutex.Lock()
	fake.stopArgsForCall = append(fake.stopArgsForCall, struct {
	}{})
	stub := fake.StopStub
	fake.recordInvocation("Stop", []interface{}{})
	fake.stopMutex.Unlock()
	if stub != nil {
		fake.StopStub()
	}
}

func (fake *FakeDecisionReplicator) StopCallCount() int {
	fake.stopMutex.RLock()
	defer fake.stopMutex.RUnlock()
	return len(fake.stopArgsForCall)
}

func (fake *FakeDecisionReplicator) StopCalls(stub func()) {
	fake.stopMutex.Lock()
	defer fake.stopMutex.Unlock()
	fake.StopStub = stub
}

func (fake *FakeDecisionReplicator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.replicateDecisionMutex.RLock()
	defer fake.replicateDecisionMutex.RUnlock()
	fake.stopMutex.RLock()
	defer fake.stopMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDecisionReplicator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ batcher.DecisionReplicator = new(FakeDecisionReplicator)
