// Code generated by counterfeiter. DO NOT EDIT.
package fake

import (
	"sync"

	"github.com/hyperledger/fabric-x-common/common/channelconfig"
	"github.com/hyperledger/fabric-x-orderer/common/deliverclient/blocksprovider"
	"github.com/hyperledger/fabric-x-orderer/common/deliverclient/orderers"
)

type EndpointsExtractor struct {
	ExtractEndpointsStub        func(channelconfig.Orderer) (orderers.Party2Endpoint, error)
	extractEndpointsMutex       sync.RWMutex
	extractEndpointsArgsForCall []struct {
		arg1 channelconfig.Orderer
	}
	extractEndpointsReturns struct {
		result1 orderers.Party2Endpoint
		result2 error
	}
	extractEndpointsReturnsOnCall map[int]struct {
		result1 orderers.Party2Endpoint
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *EndpointsExtractor) ExtractEndpoints(arg1 channelconfig.Orderer) (orderers.Party2Endpoint, error) {
	fake.extractEndpointsMutex.Lock()
	ret, specificReturn := fake.extractEndpointsReturnsOnCall[len(fake.extractEndpointsArgsForCall)]
	fake.extractEndpointsArgsForCall = append(fake.extractEndpointsArgsForCall, struct {
		arg1 channelconfig.Orderer
	}{arg1})
	stub := fake.ExtractEndpointsStub
	fakeReturns := fake.extractEndpointsReturns
	fake.recordInvocation("ExtractEndpoints", []interface{}{arg1})
	fake.extractEndpointsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *EndpointsExtractor) ExtractEndpointsCallCount() int {
	fake.extractEndpointsMutex.RLock()
	defer fake.extractEndpointsMutex.RUnlock()
	return len(fake.extractEndpointsArgsForCall)
}

func (fake *EndpointsExtractor) ExtractEndpointsCalls(stub func(channelconfig.Orderer) (orderers.Party2Endpoint, error)) {
	fake.extractEndpointsMutex.Lock()
	defer fake.extractEndpointsMutex.Unlock()
	fake.ExtractEndpointsStub = stub
}

func (fake *EndpointsExtractor) ExtractEndpointsArgsForCall(i int) channelconfig.Orderer {
	fake.extractEndpointsMutex.RLock()
	defer fake.extractEndpointsMutex.RUnlock()
	argsForCall := fake.extractEndpointsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *EndpointsExtractor) ExtractEndpointsReturns(result1 orderers.Party2Endpoint, result2 error) {
	fake.extractEndpointsMutex.Lock()
	defer fake.extractEndpointsMutex.Unlock()
	fake.ExtractEndpointsStub = nil
	fake.extractEndpointsReturns = struct {
		result1 orderers.Party2Endpoint
		result2 error
	}{result1, result2}
}

func (fake *EndpointsExtractor) ExtractEndpointsReturnsOnCall(i int, result1 orderers.Party2Endpoint, result2 error) {
	fake.extractEndpointsMutex.Lock()
	defer fake.extractEndpointsMutex.Unlock()
	fake.ExtractEndpointsStub = nil
	if fake.extractEndpointsReturnsOnCall == nil {
		fake.extractEndpointsReturnsOnCall = make(map[int]struct {
			result1 orderers.Party2Endpoint
			result2 error
		})
	}
	fake.extractEndpointsReturnsOnCall[i] = struct {
		result1 orderers.Party2Endpoint
		result2 error
	}{result1, result2}
}

func (fake *EndpointsExtractor) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.extractEndpointsMutex.RLock()
	defer fake.extractEndpointsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *EndpointsExtractor) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ blocksprovider.EndpointsExtractor = new(EndpointsExtractor)
