//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.31.1
// source: node/protos/state/assembler.proto

package state

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AssemblerBlockMetadata represents metadata about a batch that is stored in the assembler's block metadata.
// This metadata is stored in the ORDERER metadata index of Fabric blocks created by the assembler.
type AssemblerBlockMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shard            uint32 `protobuf:"varint,1,opt,name=shard,proto3" json:"shard,omitempty"`                                               // Shard ID where the batch was created
	Primary          uint32 `protobuf:"varint,2,opt,name=primary,proto3" json:"primary,omitempty"`                                           // Primary party ID that created the batch
	Sequence         uint64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`                                         // Batch sequence number within the shard created by the primary
	DecisionNum      uint64 `protobuf:"varint,4,opt,name=decision_num,json=decisionNum,proto3" json:"decision_num,omitempty"`                // Consensus decision number that ordered this batch
	BatchIndex       uint32 `protobuf:"varint,5,opt,name=batch_index,json=batchIndex,proto3" json:"batch_index,omitempty"`                   // Index of this batch within the decision (0-based)
	BatchCount       uint32 `protobuf:"varint,6,opt,name=batch_count,json=batchCount,proto3" json:"batch_count,omitempty"`                   // Total number of batches in the decision
	TransactionCount uint64 `protobuf:"varint,7,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"` // Total (cumulative) number of transactions
}

func (x *AssemblerBlockMetadata) Reset() {
	*x = AssemblerBlockMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_protos_state_assembler_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssemblerBlockMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssemblerBlockMetadata) ProtoMessage() {}

func (x *AssemblerBlockMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_node_protos_state_assembler_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssemblerBlockMetadata.ProtoReflect.Descriptor instead.
func (*AssemblerBlockMetadata) Descriptor() ([]byte, []int) {
	return file_node_protos_state_assembler_proto_rawDescGZIP(), []int{0}
}

func (x *AssemblerBlockMetadata) GetShard() uint32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *AssemblerBlockMetadata) GetPrimary() uint32 {
	if x != nil {
		return x.Primary
	}
	return 0
}

func (x *AssemblerBlockMetadata) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *AssemblerBlockMetadata) GetDecisionNum() uint64 {
	if x != nil {
		return x.DecisionNum
	}
	return 0
}

func (x *AssemblerBlockMetadata) GetBatchIndex() uint32 {
	if x != nil {
		return x.BatchIndex
	}
	return 0
}

func (x *AssemblerBlockMetadata) GetBatchCount() uint32 {
	if x != nil {
		return x.BatchCount
	}
	return 0
}

func (x *AssemblerBlockMetadata) GetTransactionCount() uint64 {
	if x != nil {
		return x.TransactionCount
	}
	return 0
}

var File_node_protos_state_assembler_proto protoreflect.FileDescriptor

var file_node_protos_state_assembler_proto_rawDesc = []byte{
	0x0a, 0x21, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x2f, 0x61, 0x73, 0x73, 0x65, 0x6d, 0x62, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0xf6, 0x01, 0x0a, 0x16, 0x41,
	0x73, 0x73, 0x65, 0x6d, 0x62, 0x6c, 0x65, 0x72, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x70, 0x72,
	0x69, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x75,
	0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x4e, 0x75, 0x6d, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x62, 0x61, 0x74, 0x63, 0x68,
	0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x62, 0x61, 0x74, 0x63,
	0x68, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2b, 0x0a, 0x11, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x10, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x68, 0x79, 0x70, 0x65, 0x72, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x66, 0x61,
	0x62, 0x72, 0x69, 0x63, 0x2d, 0x78, 0x2d, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x65, 0x72, 0x2f, 0x6e,
	0x6f, 0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_node_protos_state_assembler_proto_rawDescOnce sync.Once
	file_node_protos_state_assembler_proto_rawDescData = file_node_protos_state_assembler_proto_rawDesc
)

func file_node_protos_state_assembler_proto_rawDescGZIP() []byte {
	file_node_protos_state_assembler_proto_rawDescOnce.Do(func() {
		file_node_protos_state_assembler_proto_rawDescData = protoimpl.X.CompressGZIP(file_node_protos_state_assembler_proto_rawDescData)
	})
	return file_node_protos_state_assembler_proto_rawDescData
}

var file_node_protos_state_assembler_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_node_protos_state_assembler_proto_goTypes = []interface{}{
	(*AssemblerBlockMetadata)(nil), // 0: state.AssemblerBlockMetadata
}
var file_node_protos_state_assembler_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_node_protos_state_assembler_proto_init() }
func file_node_protos_state_assembler_proto_init() {
	if File_node_protos_state_assembler_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_node_protos_state_assembler_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssemblerBlockMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_node_protos_state_assembler_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_protos_state_assembler_proto_goTypes,
		DependencyIndexes: file_node_protos_state_assembler_proto_depIdxs,
		MessageInfos:      file_node_protos_state_assembler_proto_msgTypes,
	}.Build()
	File_node_protos_state_assembler_proto = out.File
	file_node_protos_state_assembler_proto_rawDesc = nil
	file_node_protos_state_assembler_proto_goTypes = nil
	file_node_protos_state_assembler_proto_depIdxs = nil
}
