//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.31.1
// source: node/protos/state/header.proto

package state

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Header represents the header of a proposal as part of a consensus decision
type Header struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num                          uint64   `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`                                                                                               // Decision number
	DecisionNumOfLastConfigBlock uint64   `protobuf:"varint,2,opt,name=decision_num_of_last_config_block,json=decisionNumOfLastConfigBlock,proto3" json:"decision_num_of_last_config_block,omitempty"` // Decision number of the last config block
	PrevHash                     []byte   `protobuf:"bytes,3,opt,name=prev_hash,json=prevHash,proto3" json:"prev_hash,omitempty"`                                                                      // Hash of the previous decision
	AvailableCommonBlocks        [][]byte `protobuf:"bytes,4,rep,name=available_common_blocks,json=availableCommonBlocks,proto3" json:"available_common_blocks,omitempty"`                             // Available common blocks (serialized)
	State                        []byte   `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`                                                                                            // Serialized state
}

func (x *Header) Reset() {
	*x = Header{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_protos_state_header_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_node_protos_state_header_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_node_protos_state_header_proto_rawDescGZIP(), []int{0}
}

func (x *Header) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *Header) GetDecisionNumOfLastConfigBlock() uint64 {
	if x != nil {
		return x.DecisionNumOfLastConfigBlock
	}
	return 0
}

func (x *Header) GetPrevHash() []byte {
	if x != nil {
		return x.PrevHash
	}
	return nil
}

func (x *Header) GetAvailableCommonBlocks() [][]byte {
	if x != nil {
		return x.AvailableCommonBlocks
	}
	return nil
}

func (x *Header) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

var File_node_protos_state_header_proto protoreflect.FileDescriptor

var file_node_protos_state_header_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x2f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0xce, 0x01, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x03, 0x6e, 0x75, 0x6d, 0x12, 0x47, 0x0a, 0x21, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x6e, 0x75, 0x6d, 0x5f, 0x6f, 0x66, 0x5f, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x1c, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x4e, 0x75, 0x6d, 0x4f, 0x66, 0x4c, 0x61,
	0x73, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1b, 0x0a,
	0x09, 0x70, 0x72, 0x65, 0x76, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x70, 0x72, 0x65, 0x76, 0x48, 0x61, 0x73, 0x68, 0x12, 0x36, 0x0a, 0x17, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x15, 0x61, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x42, 0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x79, 0x70, 0x65, 0x72, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x72, 0x2f, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x2d, 0x78, 0x2d, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x65, 0x72, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_node_protos_state_header_proto_rawDescOnce sync.Once
	file_node_protos_state_header_proto_rawDescData = file_node_protos_state_header_proto_rawDesc
)

func file_node_protos_state_header_proto_rawDescGZIP() []byte {
	file_node_protos_state_header_proto_rawDescOnce.Do(func() {
		file_node_protos_state_header_proto_rawDescData = protoimpl.X.CompressGZIP(file_node_protos_state_header_proto_rawDescData)
	})
	return file_node_protos_state_header_proto_rawDescData
}

var file_node_protos_state_header_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_node_protos_state_header_proto_goTypes = []interface{}{
	(*Header)(nil), // 0: state.Header
}
var file_node_protos_state_header_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_node_protos_state_header_proto_init() }
func file_node_protos_state_header_proto_init() {
	if File_node_protos_state_header_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_node_protos_state_header_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Header); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_node_protos_state_header_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_protos_state_header_proto_goTypes,
		DependencyIndexes: file_node_protos_state_header_proto_depIdxs,
		MessageInfos:      file_node_protos_state_header_proto_msgTypes,
	}.Build()
	File_node_protos_state_header_proto = out.File
	file_node_protos_state_header_proto_rawDesc = nil
	file_node_protos_state_header_proto_goTypes = nil
	file_node_protos_state_header_proto_depIdxs = nil
}
