//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.31.1
// source: node/protos/state/state.proto

package state

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ShardTerm represents a shard and its term
type ShardTerm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shard uint32 `protobuf:"varint,1,opt,name=shard,proto3" json:"shard,omitempty"`
	Term  uint64 `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
}

func (x *ShardTerm) Reset() {
	*x = ShardTerm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_protos_state_state_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShardTerm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardTerm) ProtoMessage() {}

func (x *ShardTerm) ProtoReflect() protoreflect.Message {
	mi := &file_node_protos_state_state_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardTerm.ProtoReflect.Descriptor instead.
func (*ShardTerm) Descriptor() ([]byte, []int) {
	return file_node_protos_state_state_proto_rawDescGZIP(), []int{0}
}

func (x *ShardTerm) GetShard() uint32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *ShardTerm) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

// Complaint represents a complaint about a batcher
type Complaint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigSeq uint64 `protobuf:"varint,1,opt,name=config_seq,json=configSeq,proto3" json:"config_seq,omitempty"`
	Shard     uint32 `protobuf:"varint,2,opt,name=shard,proto3" json:"shard,omitempty"`
	Term      uint64 `protobuf:"varint,3,opt,name=term,proto3" json:"term,omitempty"`
	Signer    uint32 `protobuf:"varint,4,opt,name=signer,proto3" json:"signer,omitempty"`
	Signature []byte `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	Reason    string `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *Complaint) Reset() {
	*x = Complaint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_protos_state_state_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Complaint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Complaint) ProtoMessage() {}

func (x *Complaint) ProtoReflect() protoreflect.Message {
	mi := &file_node_protos_state_state_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Complaint.ProtoReflect.Descriptor instead.
func (*Complaint) Descriptor() ([]byte, []int) {
	return file_node_protos_state_state_proto_rawDescGZIP(), []int{1}
}

func (x *Complaint) GetConfigSeq() uint64 {
	if x != nil {
		return x.ConfigSeq
	}
	return 0
}

func (x *Complaint) GetShard() uint32 {
	if x != nil {
		return x.Shard
	}
	return 0
}

func (x *Complaint) GetTerm() uint64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Complaint) GetSigner() uint32 {
	if x != nil {
		return x.Signer
	}
	return 0
}

func (x *Complaint) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Complaint) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// State represents the state of the consensus
type State struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumberOfParties uint32       `protobuf:"varint,1,opt,name=number_of_parties,json=numberOfParties,proto3" json:"number_of_parties,omitempty"`
	Shards          []*ShardTerm `protobuf:"bytes,2,rep,name=shards,proto3" json:"shards,omitempty"`                           // The different shards and their current terms
	Pending         [][]byte     `protobuf:"bytes,3,rep,name=pending,proto3" json:"pending,omitempty"`                         // Pending batch attestation fragments received by consenters from batchers
	Complaints      []*Complaint `protobuf:"bytes,4,rep,name=complaints,proto3" json:"complaints,omitempty"`                   // Complaints received by consenters from batchers
	AppContext      []byte       `protobuf:"bytes,5,opt,name=app_context,json=appContext,proto3" json:"app_context,omitempty"` // Auxiliary data that may be served as context to the application
}

func (x *State) Reset() {
	*x = State{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_protos_state_state_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_node_protos_state_state_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_node_protos_state_state_proto_rawDescGZIP(), []int{2}
}

func (x *State) GetNumberOfParties() uint32 {
	if x != nil {
		return x.NumberOfParties
	}
	return 0
}

func (x *State) GetShards() []*ShardTerm {
	if x != nil {
		return x.Shards
	}
	return nil
}

func (x *State) GetPending() [][]byte {
	if x != nil {
		return x.Pending
	}
	return nil
}

func (x *State) GetComplaints() []*Complaint {
	if x != nil {
		return x.Complaints
	}
	return nil
}

func (x *State) GetAppContext() []byte {
	if x != nil {
		return x.AppContext
	}
	return nil
}

var File_node_protos_state_state_proto protoreflect.FileDescriptor

var file_node_protos_state_state_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x35, 0x0a, 0x09, 0x53, 0x68, 0x61, 0x72, 0x64, 0x54,
	0x65, 0x72, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x72,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x22, 0xa2, 0x01,
	0x0a, 0x09, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x73, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x53, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x68,
	0x61, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x68, 0x61, 0x72, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x72, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04,
	0x74, 0x65, 0x72, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x22, 0xca, 0x01, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x0a, 0x11,
	0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x5f, 0x6f, 0x66, 0x5f, 0x70, 0x61, 0x72, 0x74, 0x69, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x4f,
	0x66, 0x50, 0x61, 0x72, 0x74, 0x69, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x72,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x2e, 0x53, 0x68, 0x61, 0x72, 0x64, 0x54, 0x65, 0x72, 0x6d, 0x52, 0x06, 0x73, 0x68, 0x61, 0x72,
	0x64, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x12, 0x30, 0x0a, 0x0a,
	0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x61, 0x69,
	0x6e, 0x74, 0x52, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x1f,
	0x0a, 0x0b, 0x61, 0x70, 0x70, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0a, 0x61, 0x70, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x42,
	0x3b, 0x5a, 0x39, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x79,
	0x70, 0x65, 0x72, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63,
	0x2d, 0x78, 0x2d, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x65, 0x72, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_node_protos_state_state_proto_rawDescOnce sync.Once
	file_node_protos_state_state_proto_rawDescData = file_node_protos_state_state_proto_rawDesc
)

func file_node_protos_state_state_proto_rawDescGZIP() []byte {
	file_node_protos_state_state_proto_rawDescOnce.Do(func() {
		file_node_protos_state_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_node_protos_state_state_proto_rawDescData)
	})
	return file_node_protos_state_state_proto_rawDescData
}

var file_node_protos_state_state_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_node_protos_state_state_proto_goTypes = []interface{}{
	(*ShardTerm)(nil), // 0: state.ShardTerm
	(*Complaint)(nil), // 1: state.Complaint
	(*State)(nil),     // 2: state.State
}
var file_node_protos_state_state_proto_depIdxs = []int32{
	0, // 0: state.State.shards:type_name -> state.ShardTerm
	1, // 1: state.State.complaints:type_name -> state.Complaint
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_node_protos_state_state_proto_init() }
func file_node_protos_state_state_proto_init() {
	if File_node_protos_state_state_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_node_protos_state_state_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShardTerm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_protos_state_state_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Complaint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_protos_state_state_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*State); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_node_protos_state_state_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_protos_state_state_proto_goTypes,
		DependencyIndexes: file_node_protos_state_state_proto_depIdxs,
		MessageInfos:      file_node_protos_state_state_proto_msgTypes,
	}.Build()
	File_node_protos_state_state_proto = out.File
	file_node_protos_state_state_proto_rawDesc = nil
	file_node_protos_state_state_proto_goTypes = nil
	file_node_protos_state_state_proto_depIdxs = nil
}
